/*
 * This source file was generated by the Gradle 'init' task
 *  Leaving this here as an example */
 
/*
#ifndef APP_H
#define APP_H

#include <string>

namespace SimpleChess {
    class Greeter {
        public:
        std::string greeting();
    };
}

#endif
*/
