/*
 * This source file was generated by the Gradle 'init' task
 * Leaving this here as an example 
 */
/*
#include "app.h"
#include <cassert>

int main() {
    SimpleChess::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
*/
