/*
 * This source file was generated by the Gradle 'init' task
 * Leaving this here as an example
 * */

/*
#include <iostream>
#include <stdlib.h>
#include "app.h"

std::string SimpleChess::Greeter::greeting() {
    return std::string("Hello, World!");
}

int main () {
    SimpleChess::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    return 0;
}

*/
